version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5050:5050" # Map container port 5000 to host port 5050
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - PORT=5000 # This is the container's internal port
      - MONGO_URI=mongodb://username:password@database:27017/test
      - PAGINATION_LIMIT=8
      - BASE_URL=
      - DATASET_URL=https://30hills.com/api/products.json
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000

  database:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017" # Map container port 27017 to host port 27017
